project_id = "hfjggeybwtoysaumvtpq"

[functions.aida-chat]
verify_jwt = false

[functions.search-coupons]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.aliexpress-import]
verify_jwt = false

[functions.daily-sync]
verify_jwt = false

[functions.search-intent]
verify_jwt = false

[functions.inaya-chat]
verify_jwt = false

[functions.aliexpress-coupons]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

